version: '3'
services:
  app:
    image: devops-demo-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app